#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_start", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_done", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_idle", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_ready", 1, hls_out, -1, "", "", 1),
	Port_Property("query_address0", 5, hls_out, 0, "ap_memory", "mem_address", 1),
	Port_Property("query_ce0", 1, hls_out, 0, "ap_memory", "mem_ce", 1),
	Port_Property("query_q0", 8, hls_in, 0, "ap_memory", "mem_dout", 1),
	Port_Property("query_address1", 5, hls_out, 0, "ap_memory", "MemPortADDR2", 1),
	Port_Property("query_ce1", 1, hls_out, 0, "ap_memory", "MemPortCE2", 1),
	Port_Property("query_q1", 8, hls_in, 0, "ap_memory", "MemPortDOUT2", 1),
	Port_Property("database_address0", 17, hls_out, 1, "ap_memory", "mem_address", 1),
	Port_Property("database_ce0", 1, hls_out, 1, "ap_memory", "mem_ce", 1),
	Port_Property("database_q0", 8, hls_in, 1, "ap_memory", "mem_dout", 1),
	Port_Property("max_index", 32, hls_out, 2, "ap_vld", "out_data", 1),
	Port_Property("max_index_ap_vld", 1, hls_out, 2, "ap_vld", "out_vld", 1),
	Port_Property("direction_matrix_address0", 22, hls_out, 3, "ap_memory", "mem_address", 1),
	Port_Property("direction_matrix_ce0", 1, hls_out, 3, "ap_memory", "mem_ce", 1),
	Port_Property("direction_matrix_we0", 1, hls_out, 3, "ap_memory", "mem_we", 1),
	Port_Property("direction_matrix_d0", 16, hls_out, 3, "ap_memory", "mem_din", 1),
	Port_Property("direction_matrix_address1", 22, hls_out, 3, "ap_memory", "MemPortADDR2", 1),
	Port_Property("direction_matrix_ce1", 1, hls_out, 3, "ap_memory", "MemPortCE2", 1),
	Port_Property("direction_matrix_we1", 1, hls_out, 3, "ap_memory", "MemPortWE2", 1),
	Port_Property("direction_matrix_d1", 16, hls_out, 3, "ap_memory", "MemPortDIN2", 1),
};
const char* HLS_Design_Meta::dut_name = "compute_matrices";
