# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/nbellas/interrupt_arm/interrupt_arm.srcs/sources_1/bd/lab2_simple_arm/ip/lab2_simple_arm_axi_gpio_0_2/lab2_simple_arm_axi_gpio_0_2.xci
# IP: The module: 'lab2_simple_arm_axi_gpio_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/nbellas/interrupt_arm/interrupt_arm.gen/sources_1/bd/lab2_simple_arm/ip/lab2_simple_arm_axi_gpio_0_2/lab2_simple_arm_axi_gpio_0_2_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab2_simple_arm_axi_gpio_0_2'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/nbellas/interrupt_arm/interrupt_arm.gen/sources_1/bd/lab2_simple_arm/ip/lab2_simple_arm_axi_gpio_0_2/lab2_simple_arm_axi_gpio_0_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab2_simple_arm_axi_gpio_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/nbellas/interrupt_arm/interrupt_arm.gen/sources_1/bd/lab2_simple_arm/ip/lab2_simple_arm_axi_gpio_0_2/lab2_simple_arm_axi_gpio_0_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab2_simple_arm_axi_gpio_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/nbellas/interrupt_arm/interrupt_arm.srcs/sources_1/bd/lab2_simple_arm/ip/lab2_simple_arm_axi_gpio_0_2/lab2_simple_arm_axi_gpio_0_2.xci
# IP: The module: 'lab2_simple_arm_axi_gpio_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/nbellas/interrupt_arm/interrupt_arm.gen/sources_1/bd/lab2_simple_arm/ip/lab2_simple_arm_axi_gpio_0_2/lab2_simple_arm_axi_gpio_0_2_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab2_simple_arm_axi_gpio_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/nbellas/interrupt_arm/interrupt_arm.gen/sources_1/bd/lab2_simple_arm/ip/lab2_simple_arm_axi_gpio_0_2/lab2_simple_arm_axi_gpio_0_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab2_simple_arm_axi_gpio_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/nbellas/interrupt_arm/interrupt_arm.gen/sources_1/bd/lab2_simple_arm/ip/lab2_simple_arm_axi_gpio_0_2/lab2_simple_arm_axi_gpio_0_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab2_simple_arm_axi_gpio_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
