-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
-- Version: 2020.2
-- Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity compute_matrices is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    query : IN STD_LOGIC_VECTOR (7 downto 0);
    database : IN STD_LOGIC_VECTOR (7 downto 0);
    max_index : OUT STD_LOGIC_VECTOR (31 downto 0);
    max_index_ap_vld : OUT STD_LOGIC;
    direction_matrix : OUT STD_LOGIC_VECTOR (15 downto 0);
    direction_matrix_ap_vld : OUT STD_LOGIC );
end;


architecture behav of compute_matrices is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "compute_matrices_compute_matrices,hls_ip_2020_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.297750,HLS_SYN_LAT=21637283,HLS_SYN_TPT=none,HLS_SYN_MEM=64,HLS_SYN_DSP=0,HLS_SYN_FF=390,HLS_SYN_LUT=924,HLS_VERSION=2020_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (21 downto 0) := "0000000000000000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (21 downto 0) := "0000000000000000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (21 downto 0) := "0000000000000000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (21 downto 0) := "0000000000000000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (21 downto 0) := "0000000000000000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (21 downto 0) := "0000000000000000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (21 downto 0) := "0000000000000001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (21 downto 0) := "0000000000000010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (21 downto 0) := "0000000000000100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (21 downto 0) := "0000000000001000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (21 downto 0) := "0000000000010000000000";
    constant ap_ST_fsm_state12 : STD_LOGIC_VECTOR (21 downto 0) := "0000000000100000000000";
    constant ap_ST_fsm_state13 : STD_LOGIC_VECTOR (21 downto 0) := "0000000001000000000000";
    constant ap_ST_fsm_state14 : STD_LOGIC_VECTOR (21 downto 0) := "0000000010000000000000";
    constant ap_ST_fsm_state15 : STD_LOGIC_VECTOR (21 downto 0) := "0000000100000000000000";
    constant ap_ST_fsm_state16 : STD_LOGIC_VECTOR (21 downto 0) := "0000001000000000000000";
    constant ap_ST_fsm_state17 : STD_LOGIC_VECTOR (21 downto 0) := "0000010000000000000000";
    constant ap_ST_fsm_state18 : STD_LOGIC_VECTOR (21 downto 0) := "0000100000000000000000";
    constant ap_ST_fsm_state19 : STD_LOGIC_VECTOR (21 downto 0) := "0001000000000000000000";
    constant ap_ST_fsm_state20 : STD_LOGIC_VECTOR (21 downto 0) := "0010000000000000000000";
    constant ap_ST_fsm_state21 : STD_LOGIC_VECTOR (21 downto 0) := "0100000000000000000000";
    constant ap_ST_fsm_state22 : STD_LOGIC_VECTOR (21 downto 0) := "1000000000000000000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant ap_const_lv32_E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001110";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_12 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010010";
    constant ap_const_lv32_14 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010100";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv17_0 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_11 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010001";
    constant ap_const_lv32_13 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010011";
    constant ap_const_lv32_15 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010101";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv6_1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_const_lv6_21 : STD_LOGIC_VECTOR (5 downto 0) := "100001";
    constant ap_const_lv6_20 : STD_LOGIC_VECTOR (5 downto 0) := "100000";
    constant ap_const_lv17_1 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000001";
    constant ap_const_lv17_1003E : STD_LOGIC_VECTOR (16 downto 0) := "10000000000111110";
    constant ap_const_lv17_1001F : STD_LOGIC_VECTOR (16 downto 0) := "10000000000011111";
    constant ap_const_lv5_1F : STD_LOGIC_VECTOR (4 downto 0) := "11111";
    constant ap_const_lv17_1FFFF : STD_LOGIC_VECTOR (16 downto 0) := "11111111111111111";
    constant ap_const_lv17_2 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000010";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal ap_CS_fsm : STD_LOGIC_VECTOR (21 downto 0) := "0000000000000000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal empty_8_fu_417_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal empty_11_fu_434_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal empty_14_fu_451_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal empty_16_fu_468_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal empty_18_fu_485_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal ap_CS_fsm_state10 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state10 : signal is "none";
    signal add_ln36_fu_507_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln36_reg_843 : STD_LOGIC_VECTOR (16 downto 0);
    signal ap_CS_fsm_state12 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state12 : signal is "none";
    signal add_ln42_fu_519_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln42_reg_851 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_CS_fsm_state13 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state13 : signal is "none";
    signal zext_ln37_fu_525_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln37_reg_856 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln37_fu_534_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal trunc_ln37_reg_862 : STD_LOGIC_VECTOR (4 downto 0);
    signal xor_ln72_fu_544_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal xor_ln72_reg_870 : STD_LOGIC_VECTOR (4 downto 0);
    signal icmp_ln37_fu_538_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal north_fu_582_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal north_reg_900 : STD_LOGIC_VECTOR (16 downto 0);
    signal ap_CS_fsm_state14 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state14 : signal is "none";
    signal northwest_fu_600_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal northwest_reg_906 : STD_LOGIC_VECTOR (16 downto 0);
    signal diag_array_2_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal diag_array_2_load_1_reg_912 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln48_fu_615_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln48_reg_917 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state15 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state15 : signal is "none";
    signal icmp_ln53_fu_625_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln53_reg_922 : STD_LOGIC_VECTOR (0 downto 0);
    signal max_value_4_fu_631_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal max_value_4_reg_927 : STD_LOGIC_VECTOR (16 downto 0);
    signal trunc_ln45_fu_639_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln45_reg_932 : STD_LOGIC_VECTOR (15 downto 0);
    signal empty_22_fu_730_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal empty_22_reg_940 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_CS_fsm_state17 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state17 : signal is "none";
    signal loop_index15_cast_fu_736_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal loop_index15_cast_reg_945 : STD_LOGIC_VECTOR (63 downto 0);
    signal exitcond262_fu_741_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_24_fu_747_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal empty_24_reg_958 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_CS_fsm_state19 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state19 : signal is "none";
    signal loop_index_cast_fu_753_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal loop_index_cast_reg_963 : STD_LOGIC_VECTOR (63 downto 0);
    signal exitcond273_fu_758_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln81_fu_764_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln81_reg_976 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_CS_fsm_state21 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state21 : signal is "none";
    signal icmp_ln81_fu_775_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal diag_array_1_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal diag_array_1_ce0 : STD_LOGIC;
    signal diag_array_1_we0 : STD_LOGIC;
    signal diag_array_1_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal diag_array_1_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal diag_array_2_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal diag_array_2_ce0 : STD_LOGIC;
    signal diag_array_2_we0 : STD_LOGIC;
    signal diag_array_2_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal diag_array_2_address1 : STD_LOGIC_VECTOR (5 downto 0);
    signal diag_array_2_ce1 : STD_LOGIC;
    signal diag_array_2_q1 : STD_LOGIC_VECTOR (15 downto 0);
    signal diag_array_3_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal diag_array_3_ce0 : STD_LOGIC;
    signal diag_array_3_we0 : STD_LOGIC;
    signal diag_array_3_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal diag_array_3_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal querry_buff_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal querry_buff_ce0 : STD_LOGIC;
    signal querry_buff_we0 : STD_LOGIC;
    signal querry_buff_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal database_buff_address0 : STD_LOGIC_VECTOR (16 downto 0);
    signal database_buff_ce0 : STD_LOGIC;
    signal database_buff_we0 : STD_LOGIC;
    signal database_buff_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal direction_buff_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal direction_buff_ce0 : STD_LOGIC;
    signal direction_buff_we0 : STD_LOGIC;
    signal direction_buff_d0 : STD_LOGIC_VECTOR (1 downto 0);
    signal direction_buff_q0 : STD_LOGIC_VECTOR (1 downto 0);
    signal empty_reg_306 : STD_LOGIC_VECTOR (5 downto 0);
    signal exitcond4212_fu_423_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_10_reg_317 : STD_LOGIC_VECTOR (5 downto 0);
    signal exitcond4111_fu_440_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal empty_13_reg_328 : STD_LOGIC_VECTOR (5 downto 0);
    signal exitcond4010_fu_457_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal loop_index21_reg_339 : STD_LOGIC_VECTOR (5 downto 0);
    signal exitcond399_fu_474_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal loop_index18_reg_350 : STD_LOGIC_VECTOR (16 downto 0);
    signal exitcond388_fu_491_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal k_reg_361 : STD_LOGIC_VECTOR (16 downto 0);
    signal ap_CS_fsm_state11 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state11 : signal is "none";
    signal i_reg_373 : STD_LOGIC_VECTOR (5 downto 0);
    signal icmp_ln36_fu_513_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state16 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state16 : signal is "none";
    signal loop_index15_reg_384 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_CS_fsm_state18 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state18 : signal is "none";
    signal loop_index_reg_395 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_CS_fsm_state20 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state20 : signal is "none";
    signal i_1_reg_406 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_CS_fsm_state22 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state22 : signal is "none";
    signal p_cast_fu_429_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal p_cast3_fu_446_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal p_cast4_fu_463_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal loop_index21_cast_fu_480_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal loop_index18_cast_fu_497_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln40_fu_550_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln40_1_fu_561_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln42_fu_566_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln81_fu_770_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal global_max_fu_118 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln58_fu_666_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln70_fu_698_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal max_value_fu_658_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln37_1_fu_530_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln40_fu_555_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal sext_ln41_fu_578_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal icmp_ln40_fu_572_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln42_fu_588_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal sext_ln42_fu_596_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal sext_ln43_fu_606_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal west_fu_609_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal max_value_2_fu_619_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal icmp_ln58_fu_653_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln58_fu_670_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln58_fu_684_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln58_fu_676_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal direction_fu_646_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln72_fu_704_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln72_fu_707_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln72_1_fu_713_p3 : STD_LOGIC_VECTOR (21 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (21 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component compute_matrices_diag_array_1 IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (5 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (15 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component compute_matrices_diag_array_2 IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (5 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (15 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        address1 : IN STD_LOGIC_VECTOR (5 downto 0);
        ce1 : IN STD_LOGIC;
        q1 : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component compute_matrices_querry_buff IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (4 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (7 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component compute_matrices_database_buff IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (16 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (7 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component compute_matrices_direction_buff IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (4 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (1 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (1 downto 0) );
    end component;



begin
    diag_array_1_U : component compute_matrices_diag_array_1
    generic map (
        DataWidth => 16,
        AddressRange => 33,
        AddressWidth => 6)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => diag_array_1_address0,
        ce0 => diag_array_1_ce0,
        we0 => diag_array_1_we0,
        d0 => diag_array_1_d0,
        q0 => diag_array_1_q0);

    diag_array_2_U : component compute_matrices_diag_array_2
    generic map (
        DataWidth => 16,
        AddressRange => 33,
        AddressWidth => 6)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => diag_array_2_address0,
        ce0 => diag_array_2_ce0,
        we0 => diag_array_2_we0,
        d0 => diag_array_2_d0,
        q0 => diag_array_2_q0,
        address1 => diag_array_2_address1,
        ce1 => diag_array_2_ce1,
        q1 => diag_array_2_q1);

    diag_array_3_U : component compute_matrices_diag_array_1
    generic map (
        DataWidth => 16,
        AddressRange => 33,
        AddressWidth => 6)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => diag_array_3_address0,
        ce0 => diag_array_3_ce0,
        we0 => diag_array_3_we0,
        d0 => diag_array_3_d0,
        q0 => diag_array_3_q0);

    querry_buff_U : component compute_matrices_querry_buff
    generic map (
        DataWidth => 8,
        AddressRange => 32,
        AddressWidth => 5)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => querry_buff_address0,
        ce0 => querry_buff_ce0,
        we0 => querry_buff_we0,
        d0 => query,
        q0 => querry_buff_q0);

    database_buff_U : component compute_matrices_database_buff
    generic map (
        DataWidth => 8,
        AddressRange => 65598,
        AddressWidth => 17)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => database_buff_address0,
        ce0 => database_buff_ce0,
        we0 => database_buff_we0,
        d0 => database,
        q0 => database_buff_q0);

    direction_buff_U : component compute_matrices_direction_buff
    generic map (
        DataWidth => 2,
        AddressRange => 32,
        AddressWidth => 5)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => direction_buff_address0,
        ce0 => direction_buff_ce0,
        we0 => direction_buff_we0,
        d0 => direction_buff_d0,
        q0 => direction_buff_q0);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    empty_10_reg_317_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                empty_10_reg_317 <= ap_const_lv6_0;
            elsif (((exitcond4111_fu_440_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                empty_10_reg_317 <= empty_11_fu_434_p2;
            end if; 
        end if;
    end process;

    empty_13_reg_328_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
                empty_13_reg_328 <= ap_const_lv6_0;
            elsif (((exitcond4010_fu_457_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
                empty_13_reg_328 <= empty_14_fu_451_p2;
            end if; 
        end if;
    end process;

    empty_reg_306_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((exitcond4212_fu_423_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                empty_reg_306 <= empty_8_fu_417_p2;
            elsif (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                empty_reg_306 <= ap_const_lv6_0;
            end if; 
        end if;
    end process;

    global_max_fu_118_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
                global_max_fu_118(0) <= '0';
                global_max_fu_118(1) <= '0';
                global_max_fu_118(2) <= '0';
                global_max_fu_118(3) <= '0';
                global_max_fu_118(4) <= '0';
                global_max_fu_118(5) <= '0';
                global_max_fu_118(6) <= '0';
                global_max_fu_118(7) <= '0';
                global_max_fu_118(8) <= '0';
                global_max_fu_118(9) <= '0';
                global_max_fu_118(10) <= '0';
                global_max_fu_118(11) <= '0';
                global_max_fu_118(12) <= '0';
                global_max_fu_118(13) <= '0';
                global_max_fu_118(14) <= '0';
                global_max_fu_118(15) <= '0';
            elsif (((icmp_ln70_fu_698_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state16))) then 
                                global_max_fu_118(15 downto 0) <= zext_ln58_fu_666_p1(15 downto 0);
            end if; 
        end if;
    end process;

    i_1_reg_406_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state19) and (exitcond273_fu_758_p2 = ap_const_lv1_1))) then 
                i_1_reg_406 <= ap_const_lv6_0;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state22)) then 
                i_1_reg_406 <= add_ln81_reg_976;
            end if; 
        end if;
    end process;

    i_reg_373_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state16)) then 
                i_reg_373 <= add_ln42_reg_851;
            elsif (((icmp_ln36_fu_513_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state12))) then 
                i_reg_373 <= ap_const_lv6_0;
            end if; 
        end if;
    end process;

    k_reg_361_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
                k_reg_361 <= ap_const_lv17_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state21) and (icmp_ln81_fu_775_p2 = ap_const_lv1_1))) then 
                k_reg_361 <= add_ln36_reg_843;
            end if; 
        end if;
    end process;

    loop_index15_reg_384_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state13) and (icmp_ln37_fu_538_p2 = ap_const_lv1_1))) then 
                loop_index15_reg_384 <= ap_const_lv6_0;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state18)) then 
                loop_index15_reg_384 <= empty_22_reg_940;
            end if; 
        end if;
    end process;

    loop_index18_reg_350_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
                loop_index18_reg_350 <= ap_const_lv17_0;
            elsif (((exitcond388_fu_491_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
                loop_index18_reg_350 <= empty_18_fu_485_p2;
            end if; 
        end if;
    end process;

    loop_index21_reg_339_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
                loop_index21_reg_339 <= ap_const_lv6_0;
            elsif (((exitcond399_fu_474_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state8))) then 
                loop_index21_reg_339 <= empty_16_fu_468_p2;
            end if; 
        end if;
    end process;

    loop_index_reg_395_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state17) and (exitcond262_fu_741_p2 = ap_const_lv1_1))) then 
                loop_index_reg_395 <= ap_const_lv6_0;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state20)) then 
                loop_index_reg_395 <= empty_24_reg_958;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state12)) then
                add_ln36_reg_843 <= add_ln36_fu_507_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state13)) then
                add_ln42_reg_851 <= add_ln42_fu_519_p2;
                trunc_ln37_reg_862 <= trunc_ln37_fu_534_p1;
                    zext_ln37_reg_856(5 downto 0) <= zext_ln37_fu_525_p1(5 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state21)) then
                add_ln81_reg_976 <= add_ln81_fu_764_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state14)) then
                diag_array_2_load_1_reg_912 <= diag_array_2_q0;
                north_reg_900 <= north_fu_582_p2;
                northwest_reg_906 <= northwest_fu_600_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state17)) then
                empty_22_reg_940 <= empty_22_fu_730_p2;
                    loop_index15_cast_reg_945(5 downto 0) <= loop_index15_cast_fu_736_p1(5 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state19)) then
                empty_24_reg_958 <= empty_24_fu_747_p2;
                    loop_index_cast_reg_963(5 downto 0) <= loop_index_cast_fu_753_p1(5 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state15)) then
                icmp_ln48_reg_917 <= icmp_ln48_fu_615_p2;
                icmp_ln53_reg_922 <= icmp_ln53_fu_625_p2;
                max_value_4_reg_927 <= max_value_4_fu_631_p3;
                trunc_ln45_reg_932 <= trunc_ln45_fu_639_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state13) and (icmp_ln37_fu_538_p2 = ap_const_lv1_0))) then
                xor_ln72_reg_870 <= xor_ln72_fu_544_p2;
            end if;
        end if;
    end process;
    zext_ln37_reg_856(63 downto 6) <= "0000000000000000000000000000000000000000000000000000000000";
    loop_index15_cast_reg_945(63 downto 6) <= "0000000000000000000000000000000000000000000000000000000000";
    loop_index_cast_reg_963(63 downto 6) <= "0000000000000000000000000000000000000000000000000000000000";
    global_max_fu_118(31 downto 16) <= "0000000000000000";

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state2, ap_CS_fsm_state4, ap_CS_fsm_state6, ap_CS_fsm_state8, ap_CS_fsm_state10, ap_CS_fsm_state12, ap_CS_fsm_state13, icmp_ln37_fu_538_p2, ap_CS_fsm_state17, exitcond262_fu_741_p2, ap_CS_fsm_state19, exitcond273_fu_758_p2, ap_CS_fsm_state21, icmp_ln81_fu_775_p2, exitcond4212_fu_423_p2, exitcond4111_fu_440_p2, exitcond4010_fu_457_p2, exitcond399_fu_474_p2, exitcond388_fu_491_p2, icmp_ln36_fu_513_p2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((exitcond4212_fu_423_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                if (((exitcond4111_fu_440_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                if (((exitcond4010_fu_457_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state6))) then
                    ap_NS_fsm <= ap_ST_fsm_state6;
                else
                    ap_NS_fsm <= ap_ST_fsm_state7;
                end if;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                if (((exitcond399_fu_474_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state8))) then
                    ap_NS_fsm <= ap_ST_fsm_state8;
                else
                    ap_NS_fsm <= ap_ST_fsm_state9;
                end if;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state10;
            when ap_ST_fsm_state10 => 
                if (((exitcond388_fu_491_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state10))) then
                    ap_NS_fsm <= ap_ST_fsm_state10;
                else
                    ap_NS_fsm <= ap_ST_fsm_state11;
                end if;
            when ap_ST_fsm_state11 => 
                ap_NS_fsm <= ap_ST_fsm_state12;
            when ap_ST_fsm_state12 => 
                if (((icmp_ln36_fu_513_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state12))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state13;
                end if;
            when ap_ST_fsm_state13 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state13) and (icmp_ln37_fu_538_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state17;
                else
                    ap_NS_fsm <= ap_ST_fsm_state14;
                end if;
            when ap_ST_fsm_state14 => 
                ap_NS_fsm <= ap_ST_fsm_state15;
            when ap_ST_fsm_state15 => 
                ap_NS_fsm <= ap_ST_fsm_state16;
            when ap_ST_fsm_state16 => 
                ap_NS_fsm <= ap_ST_fsm_state13;
            when ap_ST_fsm_state17 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state17) and (exitcond262_fu_741_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state19;
                else
                    ap_NS_fsm <= ap_ST_fsm_state18;
                end if;
            when ap_ST_fsm_state18 => 
                ap_NS_fsm <= ap_ST_fsm_state17;
            when ap_ST_fsm_state19 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state19) and (exitcond273_fu_758_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state21;
                else
                    ap_NS_fsm <= ap_ST_fsm_state20;
                end if;
            when ap_ST_fsm_state20 => 
                ap_NS_fsm <= ap_ST_fsm_state19;
            when ap_ST_fsm_state21 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state21) and (icmp_ln81_fu_775_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state12;
                else
                    ap_NS_fsm <= ap_ST_fsm_state22;
                end if;
            when ap_ST_fsm_state22 => 
                ap_NS_fsm <= ap_ST_fsm_state21;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXXXXXXXXXXXXX";
        end case;
    end process;
    add_ln36_fu_507_p2 <= std_logic_vector(unsigned(k_reg_361) + unsigned(ap_const_lv17_1));
    add_ln40_fu_555_p2 <= std_logic_vector(unsigned(zext_ln37_1_fu_530_p1) + unsigned(k_reg_361));
    add_ln42_fu_519_p2 <= std_logic_vector(unsigned(i_reg_373) + unsigned(ap_const_lv6_1));
    add_ln72_1_fu_713_p3 <= (add_ln72_fu_707_p2 & xor_ln72_reg_870);
    add_ln72_fu_707_p2 <= std_logic_vector(unsigned(zext_ln72_fu_704_p1) + unsigned(k_reg_361));
    add_ln81_fu_764_p2 <= std_logic_vector(unsigned(i_1_reg_406) + unsigned(ap_const_lv6_1));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state10 <= ap_CS_fsm(9);
    ap_CS_fsm_state11 <= ap_CS_fsm(10);
    ap_CS_fsm_state12 <= ap_CS_fsm(11);
    ap_CS_fsm_state13 <= ap_CS_fsm(12);
    ap_CS_fsm_state14 <= ap_CS_fsm(13);
    ap_CS_fsm_state15 <= ap_CS_fsm(14);
    ap_CS_fsm_state16 <= ap_CS_fsm(15);
    ap_CS_fsm_state17 <= ap_CS_fsm(16);
    ap_CS_fsm_state18 <= ap_CS_fsm(17);
    ap_CS_fsm_state19 <= ap_CS_fsm(18);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state20 <= ap_CS_fsm(19);
    ap_CS_fsm_state21 <= ap_CS_fsm(20);
    ap_CS_fsm_state22 <= ap_CS_fsm(21);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
    ap_CS_fsm_state9 <= ap_CS_fsm(8);

    ap_done_assign_proc : process(ap_CS_fsm_state12, icmp_ln36_fu_513_p2)
    begin
        if (((icmp_ln36_fu_513_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state12))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state12, icmp_ln36_fu_513_p2)
    begin
        if (((icmp_ln36_fu_513_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state12))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    database_buff_address0_assign_proc : process(ap_CS_fsm_state10, ap_CS_fsm_state13, loop_index18_cast_fu_497_p1, zext_ln40_1_fu_561_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
            database_buff_address0 <= zext_ln40_1_fu_561_p1(17 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            database_buff_address0 <= loop_index18_cast_fu_497_p1(17 - 1 downto 0);
        else 
            database_buff_address0 <= "XXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    database_buff_ce0_assign_proc : process(ap_CS_fsm_state10, ap_CS_fsm_state13)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state10) or (ap_const_logic_1 = ap_CS_fsm_state13))) then 
            database_buff_ce0 <= ap_const_logic_1;
        else 
            database_buff_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    database_buff_we0_assign_proc : process(ap_CS_fsm_state10, exitcond388_fu_491_p2)
    begin
        if (((exitcond388_fu_491_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
            database_buff_we0 <= ap_const_logic_1;
        else 
            database_buff_we0 <= ap_const_logic_0;
        end if; 
    end process;


    diag_array_1_address0_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_state13, loop_index15_cast_reg_945, ap_CS_fsm_state18, p_cast_fu_429_p1, zext_ln42_fu_566_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state18)) then 
            diag_array_1_address0 <= loop_index15_cast_reg_945(6 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
            diag_array_1_address0 <= zext_ln42_fu_566_p1(6 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            diag_array_1_address0 <= p_cast_fu_429_p1(6 - 1 downto 0);
        else 
            diag_array_1_address0 <= "XXXXXX";
        end if; 
    end process;


    diag_array_1_ce0_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_state13, ap_CS_fsm_state18)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) or (ap_const_logic_1 = ap_CS_fsm_state18) or (ap_const_logic_1 = ap_CS_fsm_state13))) then 
            diag_array_1_ce0 <= ap_const_logic_1;
        else 
            diag_array_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    diag_array_1_d0_assign_proc : process(ap_CS_fsm_state2, diag_array_2_q1, ap_CS_fsm_state18)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state18)) then 
            diag_array_1_d0 <= diag_array_2_q1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            diag_array_1_d0 <= ap_const_lv16_0;
        else 
            diag_array_1_d0 <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;


    diag_array_1_we0_assign_proc : process(ap_CS_fsm_state2, exitcond4212_fu_423_p2, ap_CS_fsm_state18)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state18) or ((exitcond4212_fu_423_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2)))) then 
            diag_array_1_we0 <= ap_const_logic_1;
        else 
            diag_array_1_we0 <= ap_const_logic_0;
        end if; 
    end process;


    diag_array_2_address0_assign_proc : process(ap_CS_fsm_state4, ap_CS_fsm_state13, loop_index_cast_reg_963, ap_CS_fsm_state20, p_cast3_fu_446_p1, zext_ln42_fu_566_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state20)) then 
            diag_array_2_address0 <= loop_index_cast_reg_963(6 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
            diag_array_2_address0 <= zext_ln42_fu_566_p1(6 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            diag_array_2_address0 <= p_cast3_fu_446_p1(6 - 1 downto 0);
        else 
            diag_array_2_address0 <= "XXXXXX";
        end if; 
    end process;


    diag_array_2_address1_assign_proc : process(ap_CS_fsm_state13, zext_ln37_fu_525_p1, ap_CS_fsm_state17, loop_index15_cast_fu_736_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state17)) then 
            diag_array_2_address1 <= loop_index15_cast_fu_736_p1(6 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
            diag_array_2_address1 <= zext_ln37_fu_525_p1(6 - 1 downto 0);
        else 
            diag_array_2_address1 <= "XXXXXX";
        end if; 
    end process;


    diag_array_2_ce0_assign_proc : process(ap_CS_fsm_state4, ap_CS_fsm_state13, ap_CS_fsm_state20)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state20) or (ap_const_logic_1 = ap_CS_fsm_state13))) then 
            diag_array_2_ce0 <= ap_const_logic_1;
        else 
            diag_array_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    diag_array_2_ce1_assign_proc : process(ap_CS_fsm_state13, ap_CS_fsm_state17)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state17) or (ap_const_logic_1 = ap_CS_fsm_state13))) then 
            diag_array_2_ce1 <= ap_const_logic_1;
        else 
            diag_array_2_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    diag_array_2_d0_assign_proc : process(ap_CS_fsm_state4, diag_array_3_q0, ap_CS_fsm_state20)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state20)) then 
            diag_array_2_d0 <= diag_array_3_q0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            diag_array_2_d0 <= ap_const_lv16_0;
        else 
            diag_array_2_d0 <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;


    diag_array_2_we0_assign_proc : process(ap_CS_fsm_state4, exitcond4111_fu_440_p2, ap_CS_fsm_state20)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state20) or ((exitcond4111_fu_440_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4)))) then 
            diag_array_2_we0 <= ap_const_logic_1;
        else 
            diag_array_2_we0 <= ap_const_logic_0;
        end if; 
    end process;


    diag_array_3_address0_assign_proc : process(ap_CS_fsm_state6, zext_ln37_reg_856, ap_CS_fsm_state19, loop_index_cast_fu_753_p1, ap_CS_fsm_state16, p_cast4_fu_463_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state19)) then 
            diag_array_3_address0 <= loop_index_cast_fu_753_p1(6 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state16)) then 
            diag_array_3_address0 <= zext_ln37_reg_856(6 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            diag_array_3_address0 <= p_cast4_fu_463_p1(6 - 1 downto 0);
        else 
            diag_array_3_address0 <= "XXXXXX";
        end if; 
    end process;


    diag_array_3_ce0_assign_proc : process(ap_CS_fsm_state6, ap_CS_fsm_state19, ap_CS_fsm_state16)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state6) or (ap_const_logic_1 = ap_CS_fsm_state16) or (ap_const_logic_1 = ap_CS_fsm_state19))) then 
            diag_array_3_ce0 <= ap_const_logic_1;
        else 
            diag_array_3_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    diag_array_3_d0_assign_proc : process(ap_CS_fsm_state6, ap_CS_fsm_state16, max_value_fu_658_p3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state16)) then 
            diag_array_3_d0 <= max_value_fu_658_p3;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            diag_array_3_d0 <= ap_const_lv16_0;
        else 
            diag_array_3_d0 <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;


    diag_array_3_we0_assign_proc : process(ap_CS_fsm_state6, exitcond4010_fu_457_p2, ap_CS_fsm_state16)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state16) or ((exitcond4010_fu_457_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state6)))) then 
            diag_array_3_we0 <= ap_const_logic_1;
        else 
            diag_array_3_we0 <= ap_const_logic_0;
        end if; 
    end process;


    direction_buff_address0_assign_proc : process(zext_ln37_reg_856, ap_CS_fsm_state21, ap_CS_fsm_state16, zext_ln81_fu_770_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state21)) then 
            direction_buff_address0 <= zext_ln81_fu_770_p1(5 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state16)) then 
            direction_buff_address0 <= zext_ln37_reg_856(5 - 1 downto 0);
        else 
            direction_buff_address0 <= "XXXXX";
        end if; 
    end process;


    direction_buff_ce0_assign_proc : process(ap_CS_fsm_state21, ap_CS_fsm_state16)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state16) or (ap_const_logic_1 = ap_CS_fsm_state21))) then 
            direction_buff_ce0 <= ap_const_logic_1;
        else 
            direction_buff_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    direction_buff_d0 <= 
        select_ln58_fu_676_p3 when (or_ln58_fu_684_p2(0) = '1') else 
        direction_fu_646_p3;

    direction_buff_we0_assign_proc : process(ap_CS_fsm_state16)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state16)) then 
            direction_buff_we0 <= ap_const_logic_1;
        else 
            direction_buff_we0 <= ap_const_logic_0;
        end if; 
    end process;

    direction_fu_646_p3 <= 
        ap_const_lv2_2 when (icmp_ln48_reg_917(0) = '1') else 
        ap_const_lv2_1;
    direction_matrix <= std_logic_vector(IEEE.numeric_std.resize(unsigned(direction_buff_q0),16));

    direction_matrix_ap_vld_assign_proc : process(ap_CS_fsm_state22)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state22)) then 
            direction_matrix_ap_vld <= ap_const_logic_1;
        else 
            direction_matrix_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    empty_11_fu_434_p2 <= std_logic_vector(unsigned(empty_10_reg_317) + unsigned(ap_const_lv6_1));
    empty_14_fu_451_p2 <= std_logic_vector(unsigned(empty_13_reg_328) + unsigned(ap_const_lv6_1));
    empty_16_fu_468_p2 <= std_logic_vector(unsigned(loop_index21_reg_339) + unsigned(ap_const_lv6_1));
    empty_18_fu_485_p2 <= std_logic_vector(unsigned(loop_index18_reg_350) + unsigned(ap_const_lv17_1));
    empty_22_fu_730_p2 <= std_logic_vector(unsigned(loop_index15_reg_384) + unsigned(ap_const_lv6_1));
    empty_24_fu_747_p2 <= std_logic_vector(unsigned(loop_index_reg_395) + unsigned(ap_const_lv6_1));
    empty_8_fu_417_p2 <= std_logic_vector(unsigned(empty_reg_306) + unsigned(ap_const_lv6_1));
    exitcond262_fu_741_p2 <= "1" when (loop_index15_reg_384 = ap_const_lv6_21) else "0";
    exitcond273_fu_758_p2 <= "1" when (loop_index_reg_395 = ap_const_lv6_21) else "0";
    exitcond388_fu_491_p2 <= "1" when (loop_index18_reg_350 = ap_const_lv17_1003E) else "0";
    exitcond399_fu_474_p2 <= "1" when (loop_index21_reg_339 = ap_const_lv6_20) else "0";
    exitcond4010_fu_457_p2 <= "1" when (empty_13_reg_328 = ap_const_lv6_21) else "0";
    exitcond4111_fu_440_p2 <= "1" when (empty_10_reg_317 = ap_const_lv6_21) else "0";
    exitcond4212_fu_423_p2 <= "1" when (empty_reg_306 = ap_const_lv6_21) else "0";
    icmp_ln36_fu_513_p2 <= "1" when (k_reg_361 = ap_const_lv17_1001F) else "0";
    icmp_ln37_fu_538_p2 <= "1" when (i_reg_373 = ap_const_lv6_20) else "0";
    icmp_ln40_fu_572_p2 <= "1" when (querry_buff_q0 = database_buff_q0) else "0";
    icmp_ln48_fu_615_p2 <= "1" when (signed(northwest_reg_906) > signed(north_reg_900)) else "0";
    icmp_ln53_fu_625_p2 <= "1" when (signed(west_fu_609_p2) > signed(max_value_2_fu_619_p3)) else "0";
    icmp_ln58_fu_653_p2 <= "1" when (signed(max_value_4_reg_927) < signed(ap_const_lv17_1)) else "0";
    icmp_ln70_fu_698_p2 <= "1" when (signed(zext_ln58_fu_666_p1) > signed(global_max_fu_118)) else "0";
    icmp_ln81_fu_775_p2 <= "1" when (i_1_reg_406 = ap_const_lv6_20) else "0";
    loop_index15_cast_fu_736_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(loop_index15_reg_384),64));
    loop_index18_cast_fu_497_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(loop_index18_reg_350),64));
    loop_index21_cast_fu_480_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(loop_index21_reg_339),64));
    loop_index_cast_fu_753_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(loop_index_reg_395),64));
    max_index <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln72_1_fu_713_p3),32));

    max_index_ap_vld_assign_proc : process(ap_CS_fsm_state16, icmp_ln70_fu_698_p2)
    begin
        if (((icmp_ln70_fu_698_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state16))) then 
            max_index_ap_vld <= ap_const_logic_1;
        else 
            max_index_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    max_value_2_fu_619_p3 <= 
        northwest_reg_906 when (icmp_ln48_fu_615_p2(0) = '1') else 
        north_reg_900;
    max_value_4_fu_631_p3 <= 
        west_fu_609_p2 when (icmp_ln53_fu_625_p2(0) = '1') else 
        max_value_2_fu_619_p3;
    max_value_fu_658_p3 <= 
        ap_const_lv16_0 when (icmp_ln58_fu_653_p2(0) = '1') else 
        trunc_ln45_reg_932;
    north_fu_582_p2 <= std_logic_vector(signed(sext_ln41_fu_578_p1) + signed(ap_const_lv17_1FFFF));
    northwest_fu_600_p2 <= std_logic_vector(unsigned(select_ln42_fu_588_p3) + unsigned(sext_ln42_fu_596_p1));
    or_ln58_fu_684_p2 <= (icmp_ln58_fu_653_p2 or icmp_ln53_reg_922);
    p_cast3_fu_446_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(empty_10_reg_317),64));
    p_cast4_fu_463_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(empty_13_reg_328),64));
    p_cast_fu_429_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(empty_reg_306),64));

    querry_buff_address0_assign_proc : process(ap_CS_fsm_state8, ap_CS_fsm_state13, loop_index21_cast_fu_480_p1, zext_ln40_fu_550_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
            querry_buff_address0 <= zext_ln40_fu_550_p1(5 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            querry_buff_address0 <= loop_index21_cast_fu_480_p1(5 - 1 downto 0);
        else 
            querry_buff_address0 <= "XXXXX";
        end if; 
    end process;


    querry_buff_ce0_assign_proc : process(ap_CS_fsm_state8, ap_CS_fsm_state13)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state8) or (ap_const_logic_1 = ap_CS_fsm_state13))) then 
            querry_buff_ce0 <= ap_const_logic_1;
        else 
            querry_buff_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    querry_buff_we0_assign_proc : process(ap_CS_fsm_state8, exitcond399_fu_474_p2)
    begin
        if (((exitcond399_fu_474_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            querry_buff_we0 <= ap_const_logic_1;
        else 
            querry_buff_we0 <= ap_const_logic_0;
        end if; 
    end process;

    select_ln42_fu_588_p3 <= 
        ap_const_lv17_2 when (icmp_ln40_fu_572_p2(0) = '1') else 
        ap_const_lv17_1FFFF;
    select_ln58_fu_676_p3 <= 
        ap_const_lv2_3 when (xor_ln58_fu_670_p2(0) = '1') else 
        ap_const_lv2_0;
        sext_ln41_fu_578_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(diag_array_2_q1),17));

        sext_ln42_fu_596_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(diag_array_1_q0),17));

        sext_ln43_fu_606_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(diag_array_2_load_1_reg_912),17));

    trunc_ln37_fu_534_p1 <= i_reg_373(5 - 1 downto 0);
    trunc_ln45_fu_639_p1 <= max_value_4_fu_631_p3(16 - 1 downto 0);
    west_fu_609_p2 <= std_logic_vector(signed(sext_ln43_fu_606_p1) + signed(ap_const_lv17_1FFFF));
    xor_ln58_fu_670_p2 <= (icmp_ln58_fu_653_p2 xor ap_const_lv1_1);
    xor_ln72_fu_544_p2 <= (trunc_ln37_fu_534_p1 xor ap_const_lv5_1F);
    zext_ln37_1_fu_530_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i_reg_373),17));
    zext_ln37_fu_525_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i_reg_373),64));
    zext_ln40_1_fu_561_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln40_fu_555_p2),64));
    zext_ln40_fu_550_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(xor_ln72_fu_544_p2),64));
    zext_ln42_fu_566_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln42_fu_519_p2),64));
    zext_ln58_fu_666_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(max_value_fu_658_p3),32));
    zext_ln72_fu_704_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln37_reg_862),17));
    zext_ln81_fu_770_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i_1_reg_406),64));
end behav;
