#!/usr/bin/env bash
# ****************************************************************************
# Vivado (TM) v2025.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Sat Nov 29 00:45:16 EET 2025
# SW Build 6140274 on Wed May 21 22:58:25 MDT 2025
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim test_fft_16_top_behav -key {Behavioral:sim_1:Functional:test_fft_16_top} -tclbatch test_fft_16_top.tcl -log simulate.log"
xsim test_fft_16_top_behav -key {Behavioral:sim_1:Functional:test_fft_16_top} -tclbatch test_fft_16_top.tcl -log simulate.log

