// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="compute_matrices_compute_matrices,hls_ip_2020_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.297750,HLS_SYN_LAT=21637283,HLS_SYN_TPT=none,HLS_SYN_MEM=64,HLS_SYN_DSP=0,HLS_SYN_FF=390,HLS_SYN_LUT=924,HLS_VERSION=2020_2}" *)

module compute_matrices (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        query,
        database,
        max_index,
        max_index_ap_vld,
        direction_matrix,
        direction_matrix_ap_vld
);

parameter    ap_ST_fsm_state1 = 22'd1;
parameter    ap_ST_fsm_state2 = 22'd2;
parameter    ap_ST_fsm_state3 = 22'd4;
parameter    ap_ST_fsm_state4 = 22'd8;
parameter    ap_ST_fsm_state5 = 22'd16;
parameter    ap_ST_fsm_state6 = 22'd32;
parameter    ap_ST_fsm_state7 = 22'd64;
parameter    ap_ST_fsm_state8 = 22'd128;
parameter    ap_ST_fsm_state9 = 22'd256;
parameter    ap_ST_fsm_state10 = 22'd512;
parameter    ap_ST_fsm_state11 = 22'd1024;
parameter    ap_ST_fsm_state12 = 22'd2048;
parameter    ap_ST_fsm_state13 = 22'd4096;
parameter    ap_ST_fsm_state14 = 22'd8192;
parameter    ap_ST_fsm_state15 = 22'd16384;
parameter    ap_ST_fsm_state16 = 22'd32768;
parameter    ap_ST_fsm_state17 = 22'd65536;
parameter    ap_ST_fsm_state18 = 22'd131072;
parameter    ap_ST_fsm_state19 = 22'd262144;
parameter    ap_ST_fsm_state20 = 22'd524288;
parameter    ap_ST_fsm_state21 = 22'd1048576;
parameter    ap_ST_fsm_state22 = 22'd2097152;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [7:0] query;
input  [7:0] database;
output  [31:0] max_index;
output   max_index_ap_vld;
output  [15:0] direction_matrix;
output   direction_matrix_ap_vld;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg max_index_ap_vld;
reg direction_matrix_ap_vld;

(* fsm_encoding = "none" *) reg   [21:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [5:0] empty_8_fu_417_p2;
wire    ap_CS_fsm_state2;
wire   [5:0] empty_11_fu_434_p2;
wire    ap_CS_fsm_state4;
wire   [5:0] empty_14_fu_451_p2;
wire    ap_CS_fsm_state6;
wire    ap_CS_fsm_state7;
wire   [5:0] empty_16_fu_468_p2;
wire    ap_CS_fsm_state8;
wire    ap_CS_fsm_state9;
wire   [16:0] empty_18_fu_485_p2;
wire    ap_CS_fsm_state10;
wire   [16:0] add_ln36_fu_507_p2;
reg   [16:0] add_ln36_reg_843;
wire    ap_CS_fsm_state12;
wire   [5:0] add_ln42_fu_519_p2;
reg   [5:0] add_ln42_reg_851;
wire    ap_CS_fsm_state13;
wire   [63:0] zext_ln37_fu_525_p1;
reg   [63:0] zext_ln37_reg_856;
wire   [4:0] trunc_ln37_fu_534_p1;
reg   [4:0] trunc_ln37_reg_862;
wire   [4:0] xor_ln72_fu_544_p2;
reg   [4:0] xor_ln72_reg_870;
wire   [0:0] icmp_ln37_fu_538_p2;
wire   [16:0] north_fu_582_p2;
reg   [16:0] north_reg_900;
wire    ap_CS_fsm_state14;
wire   [16:0] northwest_fu_600_p2;
reg   [16:0] northwest_reg_906;
wire   [15:0] diag_array_2_q0;
reg   [15:0] diag_array_2_load_1_reg_912;
wire   [0:0] icmp_ln48_fu_615_p2;
reg   [0:0] icmp_ln48_reg_917;
wire    ap_CS_fsm_state15;
wire   [0:0] icmp_ln53_fu_625_p2;
reg   [0:0] icmp_ln53_reg_922;
wire   [16:0] max_value_4_fu_631_p3;
reg   [16:0] max_value_4_reg_927;
wire   [15:0] trunc_ln45_fu_639_p1;
reg   [15:0] trunc_ln45_reg_932;
wire   [5:0] empty_22_fu_730_p2;
reg   [5:0] empty_22_reg_940;
wire    ap_CS_fsm_state17;
wire   [63:0] loop_index15_cast_fu_736_p1;
reg   [63:0] loop_index15_cast_reg_945;
wire   [0:0] exitcond262_fu_741_p2;
wire   [5:0] empty_24_fu_747_p2;
reg   [5:0] empty_24_reg_958;
wire    ap_CS_fsm_state19;
wire   [63:0] loop_index_cast_fu_753_p1;
reg   [63:0] loop_index_cast_reg_963;
wire   [0:0] exitcond273_fu_758_p2;
wire   [5:0] add_ln81_fu_764_p2;
reg   [5:0] add_ln81_reg_976;
wire    ap_CS_fsm_state21;
wire   [0:0] icmp_ln81_fu_775_p2;
reg   [5:0] diag_array_1_address0;
reg    diag_array_1_ce0;
reg    diag_array_1_we0;
reg   [15:0] diag_array_1_d0;
wire   [15:0] diag_array_1_q0;
reg   [5:0] diag_array_2_address0;
reg    diag_array_2_ce0;
reg    diag_array_2_we0;
reg   [15:0] diag_array_2_d0;
reg   [5:0] diag_array_2_address1;
reg    diag_array_2_ce1;
wire   [15:0] diag_array_2_q1;
reg   [5:0] diag_array_3_address0;
reg    diag_array_3_ce0;
reg    diag_array_3_we0;
reg   [15:0] diag_array_3_d0;
wire   [15:0] diag_array_3_q0;
reg   [4:0] querry_buff_address0;
reg    querry_buff_ce0;
reg    querry_buff_we0;
wire   [7:0] querry_buff_q0;
reg   [16:0] database_buff_address0;
reg    database_buff_ce0;
reg    database_buff_we0;
wire   [7:0] database_buff_q0;
reg   [4:0] direction_buff_address0;
reg    direction_buff_ce0;
reg    direction_buff_we0;
wire   [1:0] direction_buff_d0;
wire   [1:0] direction_buff_q0;
reg   [5:0] empty_reg_306;
wire   [0:0] exitcond4212_fu_423_p2;
reg   [5:0] empty_10_reg_317;
wire   [0:0] exitcond4111_fu_440_p2;
wire    ap_CS_fsm_state3;
reg   [5:0] empty_13_reg_328;
wire   [0:0] exitcond4010_fu_457_p2;
wire    ap_CS_fsm_state5;
reg   [5:0] loop_index21_reg_339;
wire   [0:0] exitcond399_fu_474_p2;
reg   [16:0] loop_index18_reg_350;
wire   [0:0] exitcond388_fu_491_p2;
reg   [16:0] k_reg_361;
wire    ap_CS_fsm_state11;
reg   [5:0] i_reg_373;
wire   [0:0] icmp_ln36_fu_513_p2;
wire    ap_CS_fsm_state16;
reg   [5:0] loop_index15_reg_384;
wire    ap_CS_fsm_state18;
reg   [5:0] loop_index_reg_395;
wire    ap_CS_fsm_state20;
reg   [5:0] i_1_reg_406;
wire    ap_CS_fsm_state22;
wire   [63:0] p_cast_fu_429_p1;
wire   [63:0] p_cast3_fu_446_p1;
wire   [63:0] p_cast4_fu_463_p1;
wire   [63:0] loop_index21_cast_fu_480_p1;
wire   [63:0] loop_index18_cast_fu_497_p1;
wire   [63:0] zext_ln40_fu_550_p1;
wire   [63:0] zext_ln40_1_fu_561_p1;
wire   [63:0] zext_ln42_fu_566_p1;
wire   [63:0] zext_ln81_fu_770_p1;
reg   [31:0] global_max_fu_118;
wire   [31:0] zext_ln58_fu_666_p1;
wire   [0:0] icmp_ln70_fu_698_p2;
wire   [15:0] max_value_fu_658_p3;
wire   [16:0] zext_ln37_1_fu_530_p1;
wire   [16:0] add_ln40_fu_555_p2;
wire  signed [16:0] sext_ln41_fu_578_p1;
wire   [0:0] icmp_ln40_fu_572_p2;
wire   [16:0] select_ln42_fu_588_p3;
wire  signed [16:0] sext_ln42_fu_596_p1;
wire  signed [16:0] sext_ln43_fu_606_p1;
wire   [16:0] west_fu_609_p2;
wire   [16:0] max_value_2_fu_619_p3;
wire   [0:0] icmp_ln58_fu_653_p2;
wire   [0:0] xor_ln58_fu_670_p2;
wire   [0:0] or_ln58_fu_684_p2;
wire   [1:0] select_ln58_fu_676_p3;
wire   [1:0] direction_fu_646_p3;
wire   [16:0] zext_ln72_fu_704_p1;
wire   [16:0] add_ln72_fu_707_p2;
wire   [21:0] add_ln72_1_fu_713_p3;
reg   [21:0] ap_NS_fsm;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 22'd1;
end

compute_matrices_diag_array_1 #(
    .DataWidth( 16 ),
    .AddressRange( 33 ),
    .AddressWidth( 6 ))
diag_array_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(diag_array_1_address0),
    .ce0(diag_array_1_ce0),
    .we0(diag_array_1_we0),
    .d0(diag_array_1_d0),
    .q0(diag_array_1_q0)
);

compute_matrices_diag_array_2 #(
    .DataWidth( 16 ),
    .AddressRange( 33 ),
    .AddressWidth( 6 ))
diag_array_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(diag_array_2_address0),
    .ce0(diag_array_2_ce0),
    .we0(diag_array_2_we0),
    .d0(diag_array_2_d0),
    .q0(diag_array_2_q0),
    .address1(diag_array_2_address1),
    .ce1(diag_array_2_ce1),
    .q1(diag_array_2_q1)
);

compute_matrices_diag_array_1 #(
    .DataWidth( 16 ),
    .AddressRange( 33 ),
    .AddressWidth( 6 ))
diag_array_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(diag_array_3_address0),
    .ce0(diag_array_3_ce0),
    .we0(diag_array_3_we0),
    .d0(diag_array_3_d0),
    .q0(diag_array_3_q0)
);

compute_matrices_querry_buff #(
    .DataWidth( 8 ),
    .AddressRange( 32 ),
    .AddressWidth( 5 ))
querry_buff_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(querry_buff_address0),
    .ce0(querry_buff_ce0),
    .we0(querry_buff_we0),
    .d0(query),
    .q0(querry_buff_q0)
);

compute_matrices_database_buff #(
    .DataWidth( 8 ),
    .AddressRange( 65598 ),
    .AddressWidth( 17 ))
database_buff_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(database_buff_address0),
    .ce0(database_buff_ce0),
    .we0(database_buff_we0),
    .d0(database),
    .q0(database_buff_q0)
);

compute_matrices_direction_buff #(
    .DataWidth( 2 ),
    .AddressRange( 32 ),
    .AddressWidth( 5 ))
direction_buff_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(direction_buff_address0),
    .ce0(direction_buff_ce0),
    .we0(direction_buff_we0),
    .d0(direction_buff_d0),
    .q0(direction_buff_q0)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        empty_10_reg_317 <= 6'd0;
    end else if (((exitcond4111_fu_440_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        empty_10_reg_317 <= empty_11_fu_434_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        empty_13_reg_328 <= 6'd0;
    end else if (((exitcond4010_fu_457_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state6))) begin
        empty_13_reg_328 <= empty_14_fu_451_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond4212_fu_423_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        empty_reg_306 <= empty_8_fu_417_p2;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        empty_reg_306 <= 6'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
                global_max_fu_118[0] <= 1'b0;
        global_max_fu_118[1] <= 1'b0;
        global_max_fu_118[2] <= 1'b0;
        global_max_fu_118[3] <= 1'b0;
        global_max_fu_118[4] <= 1'b0;
        global_max_fu_118[5] <= 1'b0;
        global_max_fu_118[6] <= 1'b0;
        global_max_fu_118[7] <= 1'b0;
        global_max_fu_118[8] <= 1'b0;
        global_max_fu_118[9] <= 1'b0;
        global_max_fu_118[10] <= 1'b0;
        global_max_fu_118[11] <= 1'b0;
        global_max_fu_118[12] <= 1'b0;
        global_max_fu_118[13] <= 1'b0;
        global_max_fu_118[14] <= 1'b0;
        global_max_fu_118[15] <= 1'b0;
    end else if (((icmp_ln70_fu_698_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state16))) begin
                global_max_fu_118[15 : 0] <= zext_ln58_fu_666_p1[15 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state19) & (exitcond273_fu_758_p2 == 1'd1))) begin
        i_1_reg_406 <= 6'd0;
    end else if ((1'b1 == ap_CS_fsm_state22)) begin
        i_1_reg_406 <= add_ln81_reg_976;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        i_reg_373 <= add_ln42_reg_851;
    end else if (((icmp_ln36_fu_513_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state12))) begin
        i_reg_373 <= 6'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        k_reg_361 <= 17'd0;
    end else if (((1'b1 == ap_CS_fsm_state21) & (icmp_ln81_fu_775_p2 == 1'd1))) begin
        k_reg_361 <= add_ln36_reg_843;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state13) & (icmp_ln37_fu_538_p2 == 1'd1))) begin
        loop_index15_reg_384 <= 6'd0;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        loop_index15_reg_384 <= empty_22_reg_940;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        loop_index18_reg_350 <= 17'd0;
    end else if (((exitcond388_fu_491_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state10))) begin
        loop_index18_reg_350 <= empty_18_fu_485_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        loop_index21_reg_339 <= 6'd0;
    end else if (((exitcond399_fu_474_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state8))) begin
        loop_index21_reg_339 <= empty_16_fu_468_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state17) & (exitcond262_fu_741_p2 == 1'd1))) begin
        loop_index_reg_395 <= 6'd0;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        loop_index_reg_395 <= empty_24_reg_958;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        add_ln36_reg_843 <= add_ln36_fu_507_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        add_ln42_reg_851 <= add_ln42_fu_519_p2;
        trunc_ln37_reg_862 <= trunc_ln37_fu_534_p1;
        zext_ln37_reg_856[5 : 0] <= zext_ln37_fu_525_p1[5 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        add_ln81_reg_976 <= add_ln81_fu_764_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        diag_array_2_load_1_reg_912 <= diag_array_2_q0;
        north_reg_900 <= north_fu_582_p2;
        northwest_reg_906 <= northwest_fu_600_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        empty_22_reg_940 <= empty_22_fu_730_p2;
        loop_index15_cast_reg_945[5 : 0] <= loop_index15_cast_fu_736_p1[5 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        empty_24_reg_958 <= empty_24_fu_747_p2;
        loop_index_cast_reg_963[5 : 0] <= loop_index_cast_fu_753_p1[5 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        icmp_ln48_reg_917 <= icmp_ln48_fu_615_p2;
        icmp_ln53_reg_922 <= icmp_ln53_fu_625_p2;
        max_value_4_reg_927 <= max_value_4_fu_631_p3;
        trunc_ln45_reg_932 <= trunc_ln45_fu_639_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state13) & (icmp_ln37_fu_538_p2 == 1'd0))) begin
        xor_ln72_reg_870 <= xor_ln72_fu_544_p2;
    end
end

always @ (*) begin
    if (((icmp_ln36_fu_513_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state12))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln36_fu_513_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state12))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        database_buff_address0 = zext_ln40_1_fu_561_p1;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        database_buff_address0 = loop_index18_cast_fu_497_p1;
    end else begin
        database_buff_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state13))) begin
        database_buff_ce0 = 1'b1;
    end else begin
        database_buff_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond388_fu_491_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state10))) begin
        database_buff_we0 = 1'b1;
    end else begin
        database_buff_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        diag_array_1_address0 = loop_index15_cast_reg_945;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        diag_array_1_address0 = zext_ln42_fu_566_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        diag_array_1_address0 = p_cast_fu_429_p1;
    end else begin
        diag_array_1_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state13))) begin
        diag_array_1_ce0 = 1'b1;
    end else begin
        diag_array_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        diag_array_1_d0 = diag_array_2_q1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        diag_array_1_d0 = 16'd0;
    end else begin
        diag_array_1_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state18) | ((exitcond4212_fu_423_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)))) begin
        diag_array_1_we0 = 1'b1;
    end else begin
        diag_array_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        diag_array_2_address0 = loop_index_cast_reg_963;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        diag_array_2_address0 = zext_ln42_fu_566_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        diag_array_2_address0 = p_cast3_fu_446_p1;
    end else begin
        diag_array_2_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        diag_array_2_address1 = loop_index15_cast_fu_736_p1;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        diag_array_2_address1 = zext_ln37_fu_525_p1;
    end else begin
        diag_array_2_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state13))) begin
        diag_array_2_ce0 = 1'b1;
    end else begin
        diag_array_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state13))) begin
        diag_array_2_ce1 = 1'b1;
    end else begin
        diag_array_2_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        diag_array_2_d0 = diag_array_3_q0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        diag_array_2_d0 = 16'd0;
    end else begin
        diag_array_2_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state20) | ((exitcond4111_fu_440_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4)))) begin
        diag_array_2_we0 = 1'b1;
    end else begin
        diag_array_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        diag_array_3_address0 = loop_index_cast_fu_753_p1;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        diag_array_3_address0 = zext_ln37_reg_856;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        diag_array_3_address0 = p_cast4_fu_463_p1;
    end else begin
        diag_array_3_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state19))) begin
        diag_array_3_ce0 = 1'b1;
    end else begin
        diag_array_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        diag_array_3_d0 = max_value_fu_658_p3;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        diag_array_3_d0 = 16'd0;
    end else begin
        diag_array_3_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state16) | ((exitcond4010_fu_457_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state6)))) begin
        diag_array_3_we0 = 1'b1;
    end else begin
        diag_array_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        direction_buff_address0 = zext_ln81_fu_770_p1;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        direction_buff_address0 = zext_ln37_reg_856;
    end else begin
        direction_buff_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state21))) begin
        direction_buff_ce0 = 1'b1;
    end else begin
        direction_buff_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        direction_buff_we0 = 1'b1;
    end else begin
        direction_buff_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        direction_matrix_ap_vld = 1'b1;
    end else begin
        direction_matrix_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln70_fu_698_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state16))) begin
        max_index_ap_vld = 1'b1;
    end else begin
        max_index_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        querry_buff_address0 = zext_ln40_fu_550_p1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        querry_buff_address0 = loop_index21_cast_fu_480_p1;
    end else begin
        querry_buff_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state13))) begin
        querry_buff_ce0 = 1'b1;
    end else begin
        querry_buff_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond399_fu_474_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state8))) begin
        querry_buff_we0 = 1'b1;
    end else begin
        querry_buff_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((exitcond4212_fu_423_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((exitcond4111_fu_440_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if (((exitcond4010_fu_457_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            if (((exitcond399_fu_474_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state8))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            if (((exitcond388_fu_491_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state10))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            if (((icmp_ln36_fu_513_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state12))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end
        end
        ap_ST_fsm_state13 : begin
            if (((1'b1 == ap_CS_fsm_state13) & (icmp_ln37_fu_538_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state17 : begin
            if (((1'b1 == ap_CS_fsm_state17) & (exitcond262_fu_741_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state19;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state19 : begin
            if (((1'b1 == ap_CS_fsm_state19) & (exitcond273_fu_758_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state21;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state20;
            end
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state21 : begin
            if (((1'b1 == ap_CS_fsm_state21) & (icmp_ln81_fu_775_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state22;
            end
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln36_fu_507_p2 = (k_reg_361 + 17'd1);

assign add_ln40_fu_555_p2 = (zext_ln37_1_fu_530_p1 + k_reg_361);

assign add_ln42_fu_519_p2 = (i_reg_373 + 6'd1);

assign add_ln72_1_fu_713_p3 = {{add_ln72_fu_707_p2}, {xor_ln72_reg_870}};

assign add_ln72_fu_707_p2 = (zext_ln72_fu_704_p1 + k_reg_361);

assign add_ln81_fu_764_p2 = (i_1_reg_406 + 6'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state21 = ap_CS_fsm[32'd20];

assign ap_CS_fsm_state22 = ap_CS_fsm[32'd21];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign direction_buff_d0 = ((or_ln58_fu_684_p2[0:0] == 1'b1) ? select_ln58_fu_676_p3 : direction_fu_646_p3);

assign direction_fu_646_p3 = ((icmp_ln48_reg_917[0:0] == 1'b1) ? 2'd2 : 2'd1);

assign direction_matrix = direction_buff_q0;

assign empty_11_fu_434_p2 = (empty_10_reg_317 + 6'd1);

assign empty_14_fu_451_p2 = (empty_13_reg_328 + 6'd1);

assign empty_16_fu_468_p2 = (loop_index21_reg_339 + 6'd1);

assign empty_18_fu_485_p2 = (loop_index18_reg_350 + 17'd1);

assign empty_22_fu_730_p2 = (loop_index15_reg_384 + 6'd1);

assign empty_24_fu_747_p2 = (loop_index_reg_395 + 6'd1);

assign empty_8_fu_417_p2 = (empty_reg_306 + 6'd1);

assign exitcond262_fu_741_p2 = ((loop_index15_reg_384 == 6'd33) ? 1'b1 : 1'b0);

assign exitcond273_fu_758_p2 = ((loop_index_reg_395 == 6'd33) ? 1'b1 : 1'b0);

assign exitcond388_fu_491_p2 = ((loop_index18_reg_350 == 17'd65598) ? 1'b1 : 1'b0);

assign exitcond399_fu_474_p2 = ((loop_index21_reg_339 == 6'd32) ? 1'b1 : 1'b0);

assign exitcond4010_fu_457_p2 = ((empty_13_reg_328 == 6'd33) ? 1'b1 : 1'b0);

assign exitcond4111_fu_440_p2 = ((empty_10_reg_317 == 6'd33) ? 1'b1 : 1'b0);

assign exitcond4212_fu_423_p2 = ((empty_reg_306 == 6'd33) ? 1'b1 : 1'b0);

assign icmp_ln36_fu_513_p2 = ((k_reg_361 == 17'd65567) ? 1'b1 : 1'b0);

assign icmp_ln37_fu_538_p2 = ((i_reg_373 == 6'd32) ? 1'b1 : 1'b0);

assign icmp_ln40_fu_572_p2 = ((querry_buff_q0 == database_buff_q0) ? 1'b1 : 1'b0);

assign icmp_ln48_fu_615_p2 = (($signed(northwest_reg_906) > $signed(north_reg_900)) ? 1'b1 : 1'b0);

assign icmp_ln53_fu_625_p2 = (($signed(west_fu_609_p2) > $signed(max_value_2_fu_619_p3)) ? 1'b1 : 1'b0);

assign icmp_ln58_fu_653_p2 = (($signed(max_value_4_reg_927) < $signed(17'd1)) ? 1'b1 : 1'b0);

assign icmp_ln70_fu_698_p2 = (($signed(zext_ln58_fu_666_p1) > $signed(global_max_fu_118)) ? 1'b1 : 1'b0);

assign icmp_ln81_fu_775_p2 = ((i_1_reg_406 == 6'd32) ? 1'b1 : 1'b0);

assign loop_index15_cast_fu_736_p1 = loop_index15_reg_384;

assign loop_index18_cast_fu_497_p1 = loop_index18_reg_350;

assign loop_index21_cast_fu_480_p1 = loop_index21_reg_339;

assign loop_index_cast_fu_753_p1 = loop_index_reg_395;

assign max_index = add_ln72_1_fu_713_p3;

assign max_value_2_fu_619_p3 = ((icmp_ln48_fu_615_p2[0:0] == 1'b1) ? northwest_reg_906 : north_reg_900);

assign max_value_4_fu_631_p3 = ((icmp_ln53_fu_625_p2[0:0] == 1'b1) ? west_fu_609_p2 : max_value_2_fu_619_p3);

assign max_value_fu_658_p3 = ((icmp_ln58_fu_653_p2[0:0] == 1'b1) ? 16'd0 : trunc_ln45_reg_932);

assign north_fu_582_p2 = ($signed(sext_ln41_fu_578_p1) + $signed(17'd131071));

assign northwest_fu_600_p2 = ($signed(select_ln42_fu_588_p3) + $signed(sext_ln42_fu_596_p1));

assign or_ln58_fu_684_p2 = (icmp_ln58_fu_653_p2 | icmp_ln53_reg_922);

assign p_cast3_fu_446_p1 = empty_10_reg_317;

assign p_cast4_fu_463_p1 = empty_13_reg_328;

assign p_cast_fu_429_p1 = empty_reg_306;

assign select_ln42_fu_588_p3 = ((icmp_ln40_fu_572_p2[0:0] == 1'b1) ? 17'd2 : 17'd131071);

assign select_ln58_fu_676_p3 = ((xor_ln58_fu_670_p2[0:0] == 1'b1) ? 2'd3 : 2'd0);

assign sext_ln41_fu_578_p1 = $signed(diag_array_2_q1);

assign sext_ln42_fu_596_p1 = $signed(diag_array_1_q0);

assign sext_ln43_fu_606_p1 = $signed(diag_array_2_load_1_reg_912);

assign trunc_ln37_fu_534_p1 = i_reg_373[4:0];

assign trunc_ln45_fu_639_p1 = max_value_4_fu_631_p3[15:0];

assign west_fu_609_p2 = ($signed(sext_ln43_fu_606_p1) + $signed(17'd131071));

assign xor_ln58_fu_670_p2 = (icmp_ln58_fu_653_p2 ^ 1'd1);

assign xor_ln72_fu_544_p2 = (trunc_ln37_fu_534_p1 ^ 5'd31);

assign zext_ln37_1_fu_530_p1 = i_reg_373;

assign zext_ln37_fu_525_p1 = i_reg_373;

assign zext_ln40_1_fu_561_p1 = add_ln40_fu_555_p2;

assign zext_ln40_fu_550_p1 = xor_ln72_fu_544_p2;

assign zext_ln42_fu_566_p1 = add_ln42_fu_519_p2;

assign zext_ln58_fu_666_p1 = max_value_fu_658_p3;

assign zext_ln72_fu_704_p1 = trunc_ln37_reg_862;

assign zext_ln81_fu_770_p1 = i_1_reg_406;

always @ (posedge ap_clk) begin
    zext_ln37_reg_856[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
    loop_index15_cast_reg_945[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
    loop_index_cast_reg_963[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
    global_max_fu_118[31:16] <= 16'b0000000000000000;
end

endmodule //compute_matrices
