# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/nbellas/fpadd_arm_2/fpadd_arm_2.srcs/sources_1/bd/lab2_simple_arm/ip/lab2_simple_arm_xbar_0/lab2_simple_arm_xbar_0.xci
# IP: The module: 'lab2_simple_arm_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/nbellas/fpadd_arm_2/fpadd_arm_2.gen/sources_1/bd/lab2_simple_arm/ip/lab2_simple_arm_xbar_0/lab2_simple_arm_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab2_simple_arm_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/nbellas/fpadd_arm_2/fpadd_arm_2.srcs/sources_1/bd/lab2_simple_arm/ip/lab2_simple_arm_xbar_0/lab2_simple_arm_xbar_0.xci
# IP: The module: 'lab2_simple_arm_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/nbellas/fpadd_arm_2/fpadd_arm_2.gen/sources_1/bd/lab2_simple_arm/ip/lab2_simple_arm_xbar_0/lab2_simple_arm_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab2_simple_arm_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
