# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/lab2_simple_arm_wrapper.xdc

# Block Designs: bd/lab2_simple_arm/lab2_simple_arm.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab2_simple_arm || ORIG_REF_NAME==lab2_simple_arm} -quiet] -quiet

# IP: bd/lab2_simple_arm/ip/lab2_simple_arm_processing_system7_0_0/lab2_simple_arm_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab2_simple_arm_processing_system7_0_0 || ORIG_REF_NAME==lab2_simple_arm_processing_system7_0_0} -quiet] -quiet

# IP: bd/lab2_simple_arm/ip/lab2_simple_arm_axi_gpio_0_2/lab2_simple_arm_axi_gpio_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab2_simple_arm_axi_gpio_0_2 || ORIG_REF_NAME==lab2_simple_arm_axi_gpio_0_2} -quiet] -quiet

# IP: bd/lab2_simple_arm/ip/lab2_simple_arm_xbar_0/lab2_simple_arm_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab2_simple_arm_xbar_0 || ORIG_REF_NAME==lab2_simple_arm_xbar_0} -quiet] -quiet

# IP: bd/lab2_simple_arm/ip/lab2_simple_arm_ps7_0_axi_periph_2/lab2_simple_arm_ps7_0_axi_periph_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab2_simple_arm_ps7_0_axi_periph_2 || ORIG_REF_NAME==lab2_simple_arm_ps7_0_axi_periph_2} -quiet] -quiet

# IP: bd/lab2_simple_arm/ip/lab2_simple_arm_rst_ps7_0_99M_2/lab2_simple_arm_rst_ps7_0_99M_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab2_simple_arm_rst_ps7_0_99M_2 || ORIG_REF_NAME==lab2_simple_arm_rst_ps7_0_99M_2} -quiet] -quiet

# IP: bd/lab2_simple_arm/ip/lab2_simple_arm_axi_gpio_0_4/lab2_simple_arm_axi_gpio_0_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab2_simple_arm_axi_gpio_0_4 || ORIG_REF_NAME==lab2_simple_arm_axi_gpio_0_4} -quiet] -quiet

# IP: bd/lab2_simple_arm/ip/lab2_simple_arm_xlconcat_0_0/lab2_simple_arm_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab2_simple_arm_xlconcat_0_0 || ORIG_REF_NAME==lab2_simple_arm_xlconcat_0_0} -quiet] -quiet

# IP: bd/lab2_simple_arm/ip/lab2_simple_arm_adder_ip_0_0/lab2_simple_arm_adder_ip_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab2_simple_arm_adder_ip_0_0 || ORIG_REF_NAME==lab2_simple_arm_adder_ip_0_0} -quiet] -quiet

# IP: bd/lab2_simple_arm/ip/lab2_simple_arm_auto_pc_0/lab2_simple_arm_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab2_simple_arm_auto_pc_0 || ORIG_REF_NAME==lab2_simple_arm_auto_pc_0} -quiet] -quiet

# XDC: /home/nbellas/fpadd_arm_2/fpadd_arm_2.gen/sources_1/bd/lab2_simple_arm/lab2_simple_arm_ooc.xdc
